### ISSUE TITLE
Lumen intermittent failure when Sessions are disabled

### ISSUE THREAD

**Issue by JoshZA** [itsgoingd/clockwork#109]
I'm using JWT Auth, and as such I'm not loading up the session middleware in lumen

I have SESSION_DRIVER=array in my .env (and confirm it's loaded)

I had to call ```$app->configure('cache');``` and remove the memcache entry to get the following stacktrace

```
[2015-09-10 07:15:36] lumen.ERROR: exception 'InvalidArgumentException' with message 'Cache store [memcached] is not defined.' in C:\xampp\htdocs\cmi_proj\vendor\illuminate\cache\CacheManager.php:91
Stack trace:
#0 C:\xampp\htdocs\cmi_proj\vendor\illuminate\cache\CacheManager.php(77): Illuminate\Cache\CacheManager->resolve('memcached')
#1 C:\xampp\htdocs\cmi_proj\vendor\illuminate\cache\CacheManager.php(55): Illuminate\Cache\CacheManager->get('memcached')
#2 C:\xampp\htdocs\cmi_proj\vendor\illuminate\cache\CacheManager.php(66): Illuminate\Cache\CacheManager->store('memcached')
#3 C:\xampp\htdocs\cmi_proj\vendor\illuminate\session\SessionManager.php(156): Illuminate\Cache\CacheManager->driver('memcached')
#4 C:\xampp\htdocs\cmi_proj\vendor\illuminate\session\SessionManager.php(143): Illuminate\Session\SessionManager->createCacheHandler('memcached')
#5 C:\xampp\htdocs\cmi_proj\vendor\illuminate\session\SessionManager.php(108): Illuminate\Session\SessionManager->createCacheBased('memcached')
#6 C:\xampp\htdocs\cmi_proj\vendor\illuminate\support\Manager.php(87): Illuminate\Session\SessionManager->createMemcachedDriver()
#7 C:\xampp\htdocs\cmi_proj\vendor\illuminate\support\Manager.php(63): Illuminate\Support\Manager->createDriver('memcached')
#8 C:\xampp\htdocs\cmi_proj\vendor\illuminate\support\Manager.php(137): Illuminate\Support\Manager->driver()
#9 C:\xampp\htdocs\cmi_proj\vendor\itsgoingd\clockwork\Clockwork\DataSource\LumenDataSource.php(214): Illuminate\Support\Manager->__call('all', Array)
#10 C:\xampp\htdocs\cmi_proj\vendor\itsgoingd\clockwork\Clockwork\DataSource\LumenDataSource.php(214): Illuminate\Session\SessionManager->all()
#11 C:\xampp\htdocs\cmi_proj\vendor\itsgoingd\clockwork\Clockwork\DataSource\LumenDataSource.php(64): Clockwork\DataSource\LumenDataSource->getSessionData()
#12 C:\xampp\htdocs\cmi_proj\vendor\itsgoingd\clockwork\Clockwork\Clockwork.php(100): Clockwork\DataSource\LumenDataSource->resolve(Object(Clockwork\Request\Request))
#13 C:\xampp\htdocs\cmi_proj\vendor\itsgoingd\clockwork\Clockwork\Support\Lumen\ClockworkSupport.php(85): Clockwork\Clockwork->resolveRequest()
#14 C:\xampp\htdocs\cmi_proj\vendor\itsgoingd\clockwork\Clockwork\Support\Lumen\ClockworkMiddleware.php(46): Clockwork\Support\Lumen\ClockworkSupport->process(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#15 [internal function]: Clockwork\Support\Lumen\ClockworkMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\xampp\htdocs\cmi_proj\vendor\illuminate\pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#17 C:\xampp\htdocs\cmi_proj\app\Http\Middleware\CorsMiddleware.php(6): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: App\Http\Middleware\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\xampp\htdocs\cmi_proj\vendor\illuminate\pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\cmi_proj\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\cmi_proj\vendor\laravel\lumen-framework\src\Application.php(1411): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 C:\xampp\htdocs\cmi_proj\vendor\laravel\lumen-framework\src\Application.php(1185): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#24 C:\xampp\htdocs\cmi_proj\vendor\laravel\lumen-framework\src\Application.php(1125): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\cmi_proj\public\index.php(36): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#26 {main}  
```

Is there a way I could stop clockwork from attempting to access sessions?

**Comment by itsgoingd** [comment]
Hey, I can't reproduce the issue by setting `SESSION_DRIVER=array`. Looks like your session driver is set to memcached for some reason, are you sure your env variables are correctly loaded and you are not overriding them somewhere in your code?

**Comment by JoshZA** [comment]
Heya, I seem to have fixed this by using

CACHE_DRIVER=file
SESSION_DRIVER=file

Not sure why that fixed it though, thanks for looking into the issue =)
