### ISSUE TITLE
[Laravel 5.2] BadMethodCallException  - Method before does not exist.

### ISSUE THREAD

**Issue by nivv** [itsgoingd/clockwork#115]
I'm trying out Clockwork with Laravel 5.2 and there seems to be a problem with the before filter in `LaravelDataSource`.

```
$this->app['router']->before(function() use($timeline)
    {
        $timeline->startEvent('dispatch', 'Router dispatch.');
    });
```

I've not seen any mention that this has been changed in Laravel 5.2, I've no idea why it throws this error.

Stacktrace:

```
[2015-12-23 08:43:55] local.ERROR: exception 'BadMethodCallException' with message 'Method before does not exist.' in /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:81
Stack trace:
#0 /home/vagrant/projects/laravel-52/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelDataSource.php(107): Illuminate\Routing\Router->__call('before', Array)
#1 /home/vagrant/projects/laravel-52/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelDataSource.php(107): Illuminate\Routing\Router->before(Object(Closure))
#2 /home/vagrant/projects/laravel-52/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkServiceProvider.php(92): Clockwork\DataSource\LaravelDataSource->listenToEvents()
#3 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(531): Clockwork\Support\Laravel\ClockworkServiceProvider->register()
#4 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(Clockwork\Support\Laravel\ClockworkServiceProvider))
#5 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(507): Illuminate\Foundation\ProviderRepository->load(Array)
#6 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#7 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#8 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#9 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#10 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#11 /home/vagrant/projects/laravel-52/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#12 {main}  
[2015-12-23 08:43:55] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Interface 'Illuminate\Contracts\Routing\Middleware' not found' in /home/vagrant/projects/laravel-52/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php:11
Stack trace:
#0 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/vagrant/projects/laravel-52/vendor/composer/ClassLoader.php(412): ()
#4 /home/vagrant/projects/laravel-52/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile()
#5 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Container/Container.php(0): Composer\Autoload\ClassLoader->loadClass()
#6 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): spl_autoload_call()
#7 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct()
#8 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build()
#9 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#10 /home/vagrant/projects/laravel-52/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(152): Illuminate\Foundation\Application->make()
#11 /home/vagrant/projects/laravel-52/public/index.php(58): Illuminate\Foundation\Http\Kernel->terminate()
#12 /home/vagrant/projects/laravel-52/public/index.php(0): {main}()
#13 {main}  
```

**Comment by itsgoingd** [comment]
Hey, I've just tagged new Clockwork 1.10 including Laravel 5.2 support, composer update should solve your issue.

**Comment by nivv** [comment]
@itsgoingd thanks! It works now! :santa:
