### ISSUE TITLE
Array to string conversion exception after upgrade to Clockwork 4

### ISSUE THREAD

**Issue by sebastiaanluca** [itsgoingd/clockwork#335]
Immediately after upgrading, I get the exception below. Did some quick digging and the only array in the payload sent to the prepare statement is an array of route middleware. Somehow that array doesn't get parsed to a string before sending it to the statement?

Exception:
```
[2019-07-15 16:55:10] local.ERROR: Array to string conversion {"userId":613,"exception":"[object] (ErrorException(code: 0): Array to string conversion at …/vendor/itsgoingd/clockwork/Clockwork/Storage/SqlStorage.php:211)
[stacktrace]
#0 …/vendor/sentry/sentry/src/ErrorHandler.php(361): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Array to string...', '…...', 211)
#1 [internal function]: Sentry\\ErrorHandler->handleError(8, 'Array to string...', '…...', 211, Array)
#2 …/vendor/itsgoingd/clockwork/Clockwork/Storage/SqlStorage.php(211): PDOStatement->execute(Array)
#3 …/vendor/itsgoingd/clockwork/Clockwork/Storage/SqlStorage.php(161): Clockwork\\Storage\\SqlStorage->query('INSERT INTO clo...', Array)
#4 …/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php(140): Clockwork\\Storage\\SqlStorage->store(Object(Clockwork\\Request\\Request))
#5 …/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkSupport.php(129): Clockwork\\Clockwork->storeRequest()
#6 …/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(33): Clockwork\\Support\\Laravel\\ClockworkSupport->process(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#7 …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#8 …/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#9 …/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 …/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#12 …/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#13 …an/.composer/vendor/laravel/valet/server.php(158): require('…...')
#14 {main}
"}
```

Redacted payload (`dd($bindings);` on line 211 in `SqlStorage.php`):
```
[
      "middleware" => array:2 [▼
        0 => "web"
        1 => "auth"
      ]
]
```

**Comment by itsgoingd** [comment]
Thanks for reporting, tagged 4.0.3 with a fix. It was indeed the middleware field not being marked for serialization.

**Comment by sebastiaanluca** [comment]
Thanks for the quick fix and tag!
