### ISSUE TITLE
Bug with laravel, when no 'web' auth manager

### ISSUE THREAD

**Issue by MordiSacks** [itsgoingd/clockwork#459]
### Enviroment
PHP: 7.4.9
OS: Debian 10
Laravel: 8.18.1
Clockwork: v5.0.4

I dont have a "web" auth guard in my app,  

Stacktrace  
```log
 local.ERROR: Auth guard [web] is not defined. {"exception":"[object] (InvalidArgumentException(code: 0): Auth guard [web] is not defined. at ....../vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php:84)
[stacktrace]
#0 /var/www/4brands/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(68): Illuminate\\Auth\\AuthManager->resolve()
#1 /var/www/4brands/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(307): Illuminate\\Auth\\AuthManager->guard()
#2 /var/www/4brands/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelDataSource.php(186): Illuminate\\Auth\\AuthManager->__call()
#3 /var/www/4brands/vendor/itsgoingd/clockwork/Clockwork/DataSource/LaravelDataSource.php(53): Clockwork\\DataSource\\LaravelDataSource->resolveAuthenticatedUser()
#4 /var/www/4brands/vendor/itsgoingd/clockwork/Clockwork/Clockwork.php(59): Clockwork\\DataSource\\LaravelDataSource->resolve()
#5 /var/www/4brands/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkSupport.php(363): Clockwork\\Clockwork->resolveRequest()
#6 /var/www/4brands/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(30): Clockwork\\Support\\Laravel\\ClockworkSupport->processRequest()
#7 /var/www/4brands/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle()
#8 /var/www/4brands/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/4brands/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#10 /var/www/4brands/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#11 /var/www/4brands/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#12 {main}
"} 
```

I believe this is related to PR #355  
maybe it should pull the guard from `config('auth.defaults.guard')`, or maybe this should be configurable

@DrBenton 

Thank you for a great project.

**Comment by MordiSacks** [comment]
Apparently, when setting the default  authguard to an existing guard, this problem is solved.
