### ISSUE TITLE
App broken when on docker

### ISSUE THREAD

**Issue by granitebps** [itsgoingd/clockwork#603]
Hi, clockwork works fine without using docker. But when using docker it shows this error:
```
Uncaught ReflectionException: Class "cache" does not exist in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:809
```

The error is gone when I uninstall clockwork.

I'm using Laravel with docker. Is there some setup I need to do when using docker with clockwork?

Thanks!

**Comment by itsgoingd** [comment]
Hey, no there's no specific setup for Docker. Unfortunately it's impossible to tell what might be the problem without at least seeing a full stack-trace for the error.

**Comment by granitebps** [comment]
Oh I'm sorry, this is the full stack-trace for the error

```
Uncaught ReflectionException: Class "cache" does not exist in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:809
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct('cache')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build('cache')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('cache', Array, true)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('cache', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('cache', Array)
#5 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(174): Illuminate\Foundation\Application->make('cache')
#6 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(133): Illuminate\Session\SessionManager->createCacheHandler('redis')
#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(115): Illuminate\Session\SessionManager->createRedisDriver()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\Support\Manager->createDriver('redis')
#9 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(52): Illuminate\Support\Manager->driver()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Session\SessionServiceProvider->Illuminate\Session\{closure}(Object(Illuminate\Foundation\Application), Array)
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('session.store', Array, true)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('session.store', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('session.store', Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\Foundation\Application->make('session.store')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\Container\Container->offsetGet('session.store')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('redirect', Array, true)
#20 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('redirect', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('redirect', Array)
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\Foundation\Application->make('redirect')
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\Container\Container->offsetGet('redirect')
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
#25 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#27 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application->make('Illuminate\\Cont...', Array)
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(747): app('Illuminate\\Cont...')
#31 /var/www/app/Exceptions/Handler.php(106): response()
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Illuminate\Contracts\Container\BindingResolutionException))
#34 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#35 {main}

Next Illuminate\Contracts\Container\BindingResolutionException: Target class [cache] does not exist. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:811
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build('cache')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('cache', Array, true)
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('cache', Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('cache', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(174): Illuminate\Foundation\Application->make('cache')
#5 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(133): Illuminate\Session\SessionManager->createCacheHandler('redis')
#6 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(115): Illuminate\Session\SessionManager->createRedisDriver()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\Support\Manager->createDriver('redis')
#8 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(52): Illuminate\Support\Manager->driver()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Session\SessionServiceProvider->Illuminate\Session\{closure}(Object(Illuminate\Foundation\Application), Array)
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('session.store', Array, true)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('session.store', Array)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('session.store', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\Foundation\Application->make('session.store')
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\Container\Container->offsetGet('session.store')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
#17 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('redirect', Array, true)
#19 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('redirect', Array)
#20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('redirect', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\Foundation\Application->make('redirect')
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\Container\Container->offsetGet('redirect')
#23 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(Illuminate\Foundation\Application), Array)
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\Container\Container->build(Object(Closure))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#26 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#27 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\Foundation\Application->make('Illuminate\\Cont...', Array)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(747): app('Illuminate\\Cont...')
#30 /var/www/app/Exceptions/Handler.php(106): response()
#31 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Illuminate\Contracts\Container\BindingResolutionException))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Illuminate\Contracts\Container\BindingResolutionException))
#33 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\Contracts\Container\BindingResolutionException))
#34 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ReflectionException: Class \"cache\" does not exist in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:809
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(809): ReflectionClass->__construct('cache')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build('cache')
#2 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('cache', Array, true)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('cache', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('cache', Array)
#5 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(174): Illuminate\\Foundation\\Application->make('cache')
#6 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(133): Illuminate\\Session\\SessionManager->createCacheHandler('redis')
#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(115): Illuminate\\Session\\SessionManager->createRedisDriver()
#8 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\\Support\\Manager->createDriver('redis')
#9 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(52): Illuminate\\Support\\Manager->driver()
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Session\\SessionServiceProvider->Illuminate\\Session\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(Object(Closure))
#12 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('session.store', Array, true)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('session.store', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('session.store', Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\\Foundation\\Application->make('session.store')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\\Container\\Container->offsetGet('session.store')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#18 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(Object(Closure))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('redirect', Array, true)
#20 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('redirect', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('redirect', Array)
#22 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\\Foundation\\Application->make('redirect')
#23 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\\Container\\Container->offsetGet('redirect')
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#25 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(Object(Closure))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('Illuminate\\\\Cont...', Array, true)
#27 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('Illuminate\\\\Cont...', Array)
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('Illuminate\\\\Cont...', Array)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Illuminate\\\\Cont...', Array)
#30 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(747): app('Illuminate\\\\Cont...')
#31 /var/www/app/Exceptions/Handler.php(106): response()
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#34 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#35 {main}

Next Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [cache] does not exist. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:811
Stack trace:
#0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build('cache')
#1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('cache', Array, true)
#2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('cache', Array)
#3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('cache', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(174): Illuminate\\Foundation\\Application->make('cache')
#5 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(133): Illuminate\\Session\\SessionManager->createCacheHandler('redis')
#6 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(115): Illuminate\\Session\\SessionManager->createRedisDriver()
#7 /var/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\\Support\\Manager->createDriver('redis')
#8 /var/www/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(52): Illuminate\\Support\\Manager->driver()
#9 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Session\\SessionServiceProvider->Illuminate\\Session\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#10 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(Object(Closure))
#11 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('session.store', Array, true)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('session.store', Array)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('session.store', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\\Foundation\\Application->make('session.store')
#15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\\Container\\Container->offsetGet('session.store')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#17 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(Object(Closure))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('redirect', Array, true)
#19 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('redirect', Array)
#20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('redirect', Array)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1283): Illuminate\\Foundation\\Application->make('redirect')
#22 /var/www/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\\Container\\Container->offsetGet('redirect')
#23 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#24 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build(Object(Closure))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve('Illuminate\\\\Cont...', Array, true)
#26 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve('Illuminate\\\\Cont...', Array)
#27 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make('Illuminate\\\\Cont...', Array)
#28 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make('Illuminate\\\\Cont...', Array)
#29 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(747): app('Illuminate\\\\Cont...')
#30 /var/www/app/Exceptions/Handler.php(106): response()
#31 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#33 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Illuminate\\Contracts\\Container\\BindingResolutionException))
#34 {main}
  thrown at /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:811)
[stacktrace]
#0 {main}
"} 
```

**Comment by syamsoul** [comment]
i have same issue..

when in your `.env` have `CLOCKWORK_STORAGE=redis`

then, you run 
```bash
docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php83-composer:latest composer install --ignore-platform-reqs
```

you will get error

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class "Redis" not found

  at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:79
     75▕      * @throws \LogicException
     76▕      */
     77▕     protected function createClient(array $config)
     78▕     {
  ➜  79▕         return tap(new Redis, function ($client) use ($config) {
     80▕             if ($client instanceof RedisFacade) {
     81▕                 throw new LogicException(
     82▕                     extension_loaded('redis')
     83▕                         ? 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'

  i   A class import is missing: You have a missing class import. Try importing this class: `Illuminate\Support\Facades\Redis`. 

      +28 vendor frames 

  29  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Clockwork\Support\Laravel\ClockworkServiceProvider), "Clockwork\Support\Laravel\ClockworkServiceProvider")
      +6 vendor frames 

  36  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by syamsoul** [comment]
> i have same issue..
> 
> when in your `.env` have `CLOCKWORK_STORAGE=redis`
> 
> then, you run
> 
> ```shell
> docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php83-composer:latest composer install --ignore-platform-reqs
> ```
> 
> you will get error
> 
> ```
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> 
>    Error 
> 
>   Class "Redis" not found
> 
>   at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:79
>      75▕      * @throws \LogicException
>      76▕      */
>      77▕     protected function createClient(array $config)
>      78▕     {
>   ➜  79▕         return tap(new Redis, function ($client) use ($config) {
>      80▕             if ($client instanceof RedisFacade) {
>      81▕                 throw new LogicException(
>      82▕                     extension_loaded('redis')
>      83▕                         ? 'Please remove or rename the Redis facade alias in your "app" configuration file in order to avoid collision with the PHP Redis extension.'
> 
>   i   A class import is missing: You have a missing class import. Try importing this class: `Illuminate\Support\Facades\Redis`. 
> 
>       +28 vendor frames 
> 
>   29  [internal]:0
>       Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Clockwork\Support\Laravel\ClockworkServiceProvider), "Clockwork\Support\Laravel\ClockworkServiceProvider")
>       +6 vendor frames 
> 
>   36  artisan:13
>       Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> ```

and I found workaround...

just add `-e CLOCKWORK_STORAGE=files` in the command....

```bash
docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html -e CLOCKWORK_STORAGE=files laravelsail/php82-composer:latest composer install --ignore-platform-reqs
```

**Comment by itsgoingd** [comment]
The last issue was caused by missing php-redis extension. Closing this old issue, please reopen if it's still a problem.
