### ISSUE TITLE
enaDataGet not working: HTTP Error 400

### ISSUE THREAD

**Issue by rpalcab** [itsgoingd/clockwork#639]
Hi!

I'm trying to download several fastq files from ENA using enaDataGet command. In the past, I've successfully done it executing the following command:

```while read -r id rest ; do ena=$(echo $id | tr -d '"'); echo $ena; singularity exec clockwork.img enaDataGet -d complementary/ -f fastq $ena; done < complementary/samples.csv```

However, I'm currently obtaining the following error:

```
ERR1082118
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/ERR1082118
Traceback (most recent call last):
  File "/bioinf-tools/enaBrowserTools/python3/enaDataGet.py", line 116, in <module>
    readGet.download_files(accession, output_format, dest_dir, fetch_index, fetch_meta, aspera)
  File "/bioinf-tools/enaBrowserTools/python3/readGet.py", line 93, in download_files
    lines = utils.download_report_from_portal(search_url)
  File "/bioinf-tools/enaBrowserTools/python3/utils.py", line 487, in download_report_from_portal
    response = get_report_from_portal(url)
  File "/bioinf-tools/enaBrowserTools/python3/utils.py", line 474, in get_report_from_portal
    response = urlrequest.urlopen(request)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: 
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
```

Has anybody encountered this issue and was able to solve it? Any hints about what could be happening? I have checked that the url (```https://www.ebi.ac.uk/ena/browser/api/xml/ERR1082118```) is accessible.

Many thanks!

**Comment by itsgoingd** [comment]
Hey, I think you are looking for some different github project. :)
